variable "acl_tokens_secret_id" {
  default     = null
  description = "Consul server ACL tokens Key Vault Secret ID"
  type        = string
}

variable "application_security_group_ids" {
  description = "Application Security Group ID for Consul Server VMs"
  type        = list(string)
}

variable "ca_cert" {
  description = "Certificate Authority public certificate (used to sign the server certs in secret \"tls_secret_id\")"
  type        = string
}

variable "create_client_identity_id" {
  default     = true
  description = "Should a managed identity with the necessary permissions for cloud auto-join and Key Vault access be created?"
  type        = bool
}

variable "common_tags" {
  default     = {}
  description = "(Optional) Map of common tags for all taggable resources"
  type        = map(string)
}

variable "consul_license_filepath" {
  description = "Path to location of consul license file"
  type        = string
}

variable "consul_version" {
  default     = "1.10.2"
  description = "Consul version"
  type        = string
}

variable "gossip_secret_id" {
  description = "ID of Key Vault Secret where the Consul gossip encryption key is stored"
  type        = string
}

variable "health_check_path" {
  default     = "/v1/status/leader"
  description = "The endpoint to check for Consul's health status"
  type        = string
}

variable "instance_count" {
  default     = 5
  description = "Number of Consul server VMs to deploy in Scale Set"
  type        = number
}

variable "instance_type" {
  default     = "Standard_D2s_v3"
  description = "Scale Set VM SKU"
  type        = string
}

variable "key_vault_id" {
  description = "Azure Key Vault containing TLS certificates and gossip key (will also be used to store Consul license)"
  type        = string
}

variable "resource_group" {
  description = "Azure resource group in which resources will be deployed"

  type = object({
    name     = string
    location = string
    id       = string
  })
}

variable "resource_name_prefix" {
  description = "Prefix applied to resource names (e.g. providing \"dev\" will create a VM Scale Set named \"dev-consul\")"
  type        = string
}

variable "scale_set_rolling_upgrade_policy" {
  description = "Server VM Scale Set rolling upgrade options (used when \"scale_set_upgrade_mode\" is set to Rolling or Automatic)"

  default = {
    max_batch_instance_percent              = 20
    max_unhealthy_instance_percent          = 20
    max_unhealthy_upgraded_instance_percent = 20
    pause_time_between_batches              = "PT1M"
  }

  type = object({
    max_batch_instance_percent              = number
    max_unhealthy_instance_percent          = number
    max_unhealthy_upgraded_instance_percent = number
    pause_time_between_batches              = string
  })
}

variable "scale_set_upgrade_mode" {
  default     = "Rolling"
  description = "Server Scale Set upgrade mode"
  type        = string
}

variable "ssh_public_key" {
  default     = ""
  description = "Public key to use for SSH access to Consul instances"
  type        = string
}

variable "ssh_username" {
  default     = "azureuser"
  description = "SSH admin username for Consul instances"
  type        = string
}

variable "subnet_id" {
  description = "Subnet where Consul servers will be deployed"
  type        = string
}

variable "tls_secret_id" {
  description = "ID of Key Vault Secret where Consul server TLS cert bundle is stored"
  type        = string
}

variable "user_supplied_source_image_id" {
  default     = null
  description = "(Optional) Image ID for Consul instances. If provided, please ensure it will work with the default userdata config (assumes latest version of Ubuntu LTS). Otherwise, please provide your own custom userdata using the user_supplied_userdata_path variable."
  type        = string
}

variable "user_supplied_userdata_path" {
  default     = null
  description = "(Optional) File path to custom server VM configuration (i.e. cloud-init config) being supplied by the user"
  type        = string
}

variable "user_supplied_identity_id" {
  default     = null
  description = "(Optional) User-provided User Assigned Identity for Consul servers. The minimum permissions must match the defaults generated by the IAM submodule for cloud auto-join and Key Vault access."
  type        = string
}

variable "ultra_ssd_enabled" {
  default     = true
  description = "Enable VM scale set Ultra SSD data disks compatibility"
  type        = bool
}

variable "zones" {
  description = "Azure availability zones for deployment"
  type        = list(string)

  default = [
    "1",
    "2",
    "3",
  ]
}
