variable "common_tags" {
  default     = {}
  description = "(Optional) Map of common tags for all taggable resources"
  type        = map(string)
}

variable "create_client_identity_id" {
  default     = true
  description = "Should a managed identity with the necessary permissions for cloud auto-join and Key Vault access be created?"
  type        = bool
}

variable "gossip_secret_id" {
  description = "Key Vault Secret containing the gossip encryption key"
  type        = string
}

variable "key_vault_id" {
  description = "Azure Key Vault in which the Consul secrets are stored"
  type        = string
}

variable "license_secret_id" {
  description = "Key Vault Secret containing the base64 encoded Consul Enterprise license file"
  type        = string
}

variable "resource_group" {
  description = "Azure resource group in which resources will be deployed"

  type = object({
    id       = string
    location = string
    name     = string
  })
}

variable "resource_name_prefix" {
  description = "Prefix applied to resource names"
  type        = string
}

variable "tenant_id" {
  description = "Tenant ID"
  type        = string
}

variable "user_supplied_identity_id" {
  default     = null
  description = "(Optional) User-provided User Assigned Identity for Consul servers. The minimum permissions must match the defaults generated by this module for cloud auto-join and access to the gossip/tls secrets."
  type        = string
}
